from django.db import models
from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.base_user import AbstractBaseUser
from .manager import UserManager
from django.dispatch import receiver
from django.db.models.signals import post_save
import uuid

# Create your models here.
def image_uoload_profile(instance,filname):
    imagename,extention =  filname.split(".")
    return "user/%s.%s"%(instance.id,extention)

class NewUser(AbstractBaseUser,PermissionsMixin):
    nom = models.CharField(max_length=50,blank=True)
    prenom = models.CharField(max_length=50,blank=True)
    phone = models.CharField(max_length=16,unique=True)
    username = models.CharField(max_length=16,unique=True,null=True)
    email = models.EmailField(max_length=50,blank=True)
    address = models.CharField(max_length=200,)
    post = models.CharField(max_length=200,null=True)
    image=models.ImageField(upload_to=image_uoload_profile ,null=True,blank=True) 
    is_active = models.BooleanField(default=True)
    verified = models.BooleanField(default=False)
    restricted = models.BooleanField(default=False)
    deleted = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    is_blocked = models.BooleanField(default=False)
    number_attempt= models.IntegerField(default=0)
    objects = UserManager()

    USERNAME_FIELD = 'username'

    REQUIRED_FIELDS = []

    def __str__(self): 
        return self.username or "N/A"

class Profile(models.Model):
    user = models.OneToOneField(NewUser, related_name='profile', on_delete=models.CASCADE)
    reset_password_token = models.CharField(max_length=50, default="", blank=True)
    reset_password_expire = models.DateTimeField(null=True, blank=True)


@receiver(post_save, sender=NewUser)
def save_profile(sender, instance, created, **kwargs):
    user = instance
    if created:
        profile = Profile(user=user)
        profile.save()     

class Prtcli(models.Model):
    NOOPER = models.CharField(max_length=100, primary_key=True)
    NUMSEQ = models.IntegerField()
    EXPL = models.CharField(max_length=100)
    DATMAJ = models.DateField(null=True, blank=True)
    EXPLMAJ = models.CharField(max_length=100, null=True, blank=True)
    VALIDE = models.CharField(max_length=1)
    DATJOUR = models.DateField()
    DATOPER = models.DateField()
    DATDERNC = models.DateField(null=True, blank=True)
    CLIPRT = models.CharField(max_length=100)
    DEVPRT = models.CharField(max_length=100, null=True, blank=True)
    NCGPRT = models.CharField(max_length=100, null=True, blank=True)
    CPTPRT = models.CharField(max_length=100, null=True, blank=True)
    MNTPRT = models.CharField(max_length=100, null=True, blank=True)
    DATDEP = models.DateField(null=True, blank=True)
    DATRMB = models.DateField(null=True, blank=True)
    TYPIND = models.CharField(max_length=100, null=True, blank=True)
    TXDB = models.CharField(max_length=100, null=True, blank=True)
    TXDBAN = models.CharField(max_length=100, null=True, blank=True)
    NJANDB = models.CharField(max_length=100, null=True, blank=True)
    PERRMB = models.CharField(max_length=100, null=True, blank=True)
    PERINT = models.CharField(max_length=100, null=True, blank=True)
    TYPCALC = models.CharField(max_length=100, null=True, blank=True)
    TYPRMB = models.CharField(max_length=100, null=True, blank=True)
    NOOPREC = models.CharField(max_length=100, null=True, blank=True)
    XCOMDEC = models.CharField(max_length=100, null=True, blank=True)
    DERNRMB = models.CharField(max_length=100, null=True, blank=True)
    TOTINT = models.CharField(max_length=100, null=True, blank=True)
    DERNDAT = models.DateField(null=True, blank=True)
    TOTRMB = models.CharField(max_length=100, null=True, blank=True)
    CPTVUE = models.CharField(max_length=100, null=True, blank=True)
    MODRMB = models.CharField(max_length=100, null=True, blank=True)
    INTDIF = models.CharField(max_length=100, null=True, blank=True)
    MODASS = models.CharField(max_length=100, null=True, blank=True)
    CPTIMP = models.CharField(max_length=100, null=True, blank=True)
    CPTASS = models.CharField(max_length=100, null=True, blank=True)
    TXASS = models.CharField(max_length=100, null=True, blank=True)
    TXT1 = models.CharField(max_length=100, null=True, blank=True)
    TXMIN = models.CharField(max_length=100, null=True, blank=True)
    TXMAX = models.CharField(max_length=100, null=True, blank=True)
    TXTAXE = models.CharField(max_length=100, null=True, blank=True)
    MODDIF = models.CharField(max_length=100, null=True, blank=True)
    CPTDEB = models.CharField(max_length=100, null=True, blank=True)
    XDOS = models.CharField(max_length=100, null=True, blank=True)
    MNTDOS = models.CharField(max_length=100, null=True, blank=True)
    CVMNTDOS = models.CharField(max_length=100, null=True, blank=True)
    XTAXDOS = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXDOS = models.CharField(max_length=100, null=True, blank=True)
    CVMNTTAXDOS = models.CharField(max_length=100, null=True, blank=True)
    TXASSINI = models.CharField(max_length=100, null=True, blank=True)
    MNTASF = models.CharField(max_length=100, null=True, blank=True)
    TXFONGAR = models.CharField(max_length=100, null=True, blank=True)
    MNTFONGAR = models.CharField(max_length=100, null=True, blank=True)
    TXFONASS = models.CharField(max_length=100, null=True, blank=True)
    MNTFONASS = models.CharField(max_length=100, null=True, blank=True)
    MNTNETCLI = models.CharField(max_length=100, null=True, blank=True)
    XRECALC = models.CharField(max_length=100, null=True, blank=True)
    TYPTAUX = models.CharField(max_length=100, null=True, blank=True)
    DATCONTR = models.DateField(null=True, blank=True)
    TXTEG = models.CharField(max_length=100, null=True, blank=True)
    MNTCONTR = models.CharField(max_length=100, null=True, blank=True)
    XRECALCD = models.CharField(max_length=100, null=True, blank=True)
    DATRMBANT = models.DateField(null=True, blank=True)
    MNTRESTDU = models.CharField(max_length=100, null=True, blank=True)
    MNTINTINT = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXINT = models.CharField(max_length=100, null=True, blank=True)
    TXPEN = models.CharField(max_length=100, null=True, blank=True)
    MNTPEN = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXPEN = models.CharField(max_length=100, null=True, blank=True)
    MNTRMBANT = models.CharField(max_length=100, null=True, blank=True)
    MNTNEWPRT = models.CharField(max_length=100, null=True, blank=True)
    TYPNEWPRT = models.CharField(max_length=100, null=True, blank=True)
    NOPRTCSET = models.CharField(max_length=100, null=True, blank=True)
    OPER = models.CharField(max_length=100, null=True, blank=True)
    CSERV = models.CharField(max_length=100, null=True, blank=True)
    CNSIGN = models.CharField(max_length=100, null=True, blank=True)
    NSIGN = models.CharField(max_length=100, null=True, blank=True)
    PSIGN = models.CharField(max_length=100, null=True, blank=True)
    TOTSIGN = models.CharField(max_length=100, null=True, blank=True)
    PSIGN11 = models.CharField(max_length=100, null=True, blank=True)
    EXPLV1 = models.CharField(max_length=100, null=True, blank=True)
    EXPLV2 = models.CharField(max_length=100, null=True, blank=True)
    EXPLV3 = models.CharField(max_length=100, null=True, blank=True)
    XPOSOPER = models.CharField(max_length=100, null=True, blank=True)
    STATE = models.CharField(max_length=100, null=True, blank=True)
    CVMNTDEP = models.CharField(max_length=100, null=True, blank=True)
    MNTAUT1 = models.CharField(max_length=100, null=True, blank=True)
    MNTAUT2 = models.CharField(max_length=100, null=True, blank=True)
    MNTAUT3 = models.CharField(max_length=100, null=True, blank=True)
    CODDCIC = models.CharField(max_length=100, null=True, blank=True)
    EXPLCI = models.CharField(max_length=100, null=True, blank=True)
    MNTINIFGV = models.CharField(max_length=100, null=True, blank=True)
    MNTPERFGV = models.CharField(max_length=100, null=True, blank=True)
    CPTECH1 = models.CharField(max_length=100, null=True, blank=True)
    PRCECH1 = models.CharField(max_length=100, null=True, blank=True)
    CPTECH2 = models.CharField(max_length=100, null=True, blank=True)
    PRCECH2 = models.CharField(max_length=100, null=True, blank=True)
    CPTECH3 = models.CharField(max_length=100, null=True, blank=True)
    PRCECH3 = models.CharField(max_length=100, null=True, blank=True)
    DATRMBFM = models.DateField(null=True, blank=True)
    CLASSIF = models.CharField(max_length=100, null=True, blank=True)
    MNTAUTH = models.CharField(max_length=100, null=True, blank=True)
    DEPASS = models.CharField(max_length=100, null=True, blank=True)
    CRSYNDIQ = models.CharField(max_length=100, null=True, blank=True)
    XNOREVDIFF = models.CharField(max_length=100, null=True, blank=True)
    DATPREMREVTX = models.DateField(null=True, blank=True)
    MANDATAIRE = models.CharField(max_length=100, null=True, blank=True)
    XTAXFONGAR = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFONGAR = models.CharField(max_length=100, null=True, blank=True)
    CVMNTTAXFONGAR = models.CharField(max_length=100, null=True, blank=True)
    XTAXFONASS = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFONASS = models.CharField(max_length=100, null=True, blank=True)
    CVMNTTAXFONASS = models.CharField(max_length=100, null=True, blank=True)
    MNTVENT = models.CharField(max_length=100, null=True, blank=True)
    MNTACH = models.CharField(max_length=100, null=True, blank=True)
    MNTACPT = models.CharField(max_length=100, null=True, blank=True)
    PXREV = models.CharField(max_length=100, null=True, blank=True)
    TXPRFTS = models.CharField(max_length=100, null=True, blank=True)
    RMBFRAIS = models.CharField(max_length=100, null=True, blank=True)
    RMBTAXE = models.CharField(max_length=100, null=True, blank=True)
    RMBPRFT = models.CharField(max_length=100, null=True, blank=True)
    MNTPRFTS = models.CharField(max_length=100, null=True, blank=True)
    XMODIFTX = models.CharField(max_length=100, null=True, blank=True)
    BIENDESC1 = models.CharField(max_length=100, null=True, blank=True)
    BIENDESC2 = models.CharField(max_length=100, null=True, blank=True)
    TAUXTIMBRE = models.CharField(max_length=100, null=True, blank=True)
    MNTTIMBRE = models.CharField(max_length=100, null=True, blank=True)
    MNTPRFTRES = models.CharField(max_length=100, null=True, blank=True)
    MNTPRFTPAY = models.CharField(max_length=100, null=True, blank=True)
    MNTMOB = models.CharField(max_length=100, null=True, blank=True)
    MNTMOBREV = models.CharField(max_length=100, null=True, blank=True)
    DATMAJMOB = models.DateField(null=True, blank=True)
    EXPLMAJMOB = models.CharField(max_length=100, null=True, blank=True)
    XMOBILISABLE = models.CharField(max_length=100, null=True, blank=True)
    BIENDESC3 = models.CharField(max_length=100, null=True, blank=True)
    BIENDESC4 = models.CharField(max_length=100, null=True, blank=True)
    BIENDESC = models.CharField(max_length=100, null=True, blank=True)
    REFREL = models.CharField(max_length=100, null=True, blank=True)
    RMBTIMBRE = models.CharField(max_length=100, null=True, blank=True)
    TAUXFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    MNTFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    XTAXFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    CVMNTTAXFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    RMBFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    RMBTAXFRAISDIV = models.CharField(max_length=100, null=True, blank=True)
    CHEFFILE = models.CharField(max_length=100, null=True, blank=True)
    BICAGENT = models.CharField(max_length=100, null=True, blank=True)
    NUMTIR = models.CharField(max_length=100, null=True, blank=True)
    NOOPERTIR = models.CharField(max_length=100, null=True, blank=True)
    OBJOPERATION = models.CharField(max_length=100, null=True, blank=True)
    MNTFRMENS = models.CharField(max_length=100, null=True, blank=True)
    NOOPERPAR = models.CharField(max_length=100, null=True, blank=True)
    NETOFF = models.CharField(max_length=100, null=True, blank=True)
    REFINANCE = models.CharField(max_length=100, null=True, blank=True)
    MOTIFREFINANCE = models.CharField(max_length=100, null=True, blank=True)
    XTAXASF = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXASF = models.CharField(max_length=100, null=True, blank=True)
    CPTDEBLOC = models.CharField(max_length=100, null=True, blank=True)
    TXDEBLOC = models.CharField(max_length=100, null=True, blank=True)
    XDEBLOCAGEMULTIPLE = models.CharField(max_length=100, null=True, blank=True)
    TAXASS = models.CharField(max_length=100, null=True, blank=True)
    TXDEBLOCMARGE = models.CharField(max_length=100, null=True, blank=True)
    TYPIJARA = models.CharField(max_length=100, null=True, blank=True)
    TRANSFERTITLE = models.CharField(max_length=100, null=True, blank=True)
    CODANN = models.CharField(max_length=100, null=True, blank=True)
    RESANN = models.CharField(max_length=100, null=True, blank=True)
    MNTTOKEN = models.CharField(max_length=100, null=True, blank=True)
    NOOPTRADING = models.CharField(max_length=100, null=True, blank=True)
    CODMINDEP = models.CharField(max_length=100, null=True, blank=True)
    CPTHB = models.CharField(max_length=100, null=True, blank=True)
    MNTSALE = models.CharField(max_length=100, null=True, blank=True)
    MNTEFFECTEDBANKASSET = models.CharField(max_length=100, null=True, blank=True)
    ASSETTYPE = models.CharField(max_length=100, null=True, blank=True)
    ACTION = models.CharField(max_length=100, null=True, blank=True)
    PREVVALSEQ = models.CharField(max_length=100, null=True, blank=True)
    XDEFERREDPERIODICITY = models.CharField(max_length=100, null=True, blank=True)
    DEFERREDPERIODICITY = models.CharField(max_length=100, null=True, blank=True)
    MNTIMPRMBANT = models.CharField(max_length=100, null=True, blank=True)
    CVMNTDEPCLI = models.CharField(max_length=100, null=True, blank=True)
    XPOSOPERCLI = models.CharField(max_length=100, null=True, blank=True)
    MNTCAPCAP = models.CharField(max_length=100, null=True, blank=True)
    SYND_AGCODE = models.CharField(max_length=100, null=True, blank=True)
    CPTIMPINT = models.CharField(max_length=100, null=True, blank=True)
    CONVENTION = models.CharField(max_length=100, null=True, blank=True)
    TITRE_LAIUS = models.CharField(max_length=100, null=True, blank=True)
    XSIGNE = models.CharField(max_length=100, null=True, blank=True)
    DEDUCTTOTUNEARNFROMHIBA = models.CharField(max_length=100, null=True, blank=True)
    SUMMNTRMBANT_UNEARNED = models.CharField(max_length=100, null=True, blank=True)
    DATRMBDIFF = models.DateField(null=True, blank=True)
    PERINTPAY = models.CharField(max_length=100, null=True, blank=True)
    RENOVACIOO = models.CharField(max_length=100, null=True, blank=True)
    TRACKREF = models.CharField(max_length=100, null=True, blank=True)
    LATE_FEE_TYPCALC = models.CharField(max_length=100, null=True, blank=True)
    MOTIF = models.CharField(max_length=100, null=True, blank=True)
    NOOPERCONT = models.CharField(max_length=100, null=True, blank=True)
    MODIF_CDR = models.CharField(max_length=100, null=True, blank=True)
    XAMORT_MANUEL = models.CharField(max_length=100, null=True, blank=True)
    MODCALCINT = models.CharField(max_length=100, null=True, blank=True)
    XLOCKOUT = models.CharField(max_length=100, null=True, blank=True)
    NBJLOCKOUT = models.CharField(max_length=100, null=True, blank=True)
    INDFLOOR = models.CharField(max_length=100, null=True, blank=True)
    VALINDFLOOR = models.CharField(max_length=100, null=True, blank=True)
    CAS = models.CharField(max_length=100, null=True, blank=True)
    XTXTAXESPECIAL = models.CharField(max_length=100, null=True, blank=True)
    XREVOLVE = models.CharField(max_length=100, null=True, blank=True)
    CPTHBK2D = models.CharField(max_length=100, null=True, blank=True)
    CPTHBK2C = models.CharField(max_length=100, null=True, blank=True)
    CPTHBREVD = models.CharField(max_length=100, null=True, blank=True)
    CPTHBREVC = models.CharField(max_length=100, null=True, blank=True)
    CPTHBCAPD = models.CharField(max_length=100, null=True, blank=True)
    CPTHBCAPC = models.CharField(max_length=100, null=True, blank=True)
    TYPINDIMP = models.CharField(max_length=100, null=True, blank=True)
    TXDBIMP = models.CharField(max_length=100, null=True, blank=True)
    COEDBIMP = models.CharField(max_length=100, null=True, blank=True)
    MNTINTIMP = models.CharField(max_length=100, null=True, blank=True)
    MNTINTIMPTAX = models.CharField(max_length=100, null=True, blank=True)
    MNTMRGIMP = models.CharField(max_length=100, null=True, blank=True)
    MNTMRGIMPTAX = models.CharField(max_length=100, null=True, blank=True)
    LOOKBACK = models.CharField(max_length=100, null=True, blank=True)
    MNTINTIMPINT = models.CharField(max_length=100, null=True, blank=True)
    MNTINTIMPINTTAX = models.CharField(max_length=100, null=True, blank=True)
    MNTMRGIMPINT = models.CharField(max_length=100, null=True, blank=True)
    MNTMRGIMPINTTAX = models.CharField(max_length=100, null=True, blank=True)
    MNTFRSIMP = models.CharField(max_length=100, null=True, blank=True)
    MNTFRSIMPTAX = models.CharField(max_length=100, null=True, blank=True)
    BASMRGIMP = models.CharField(max_length=100, null=True, blank=True)
    MNTFR2COMMENT = models.CharField(max_length=100, null=True, blank=True)
    MNTFR2DATEFF = models.DateField(null=True, blank=True)
    MNTFR2PER = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFR2 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR2 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR4DATEFF = models.DateField(null=True, blank=True)
    MNTFR4PER = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFR4 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR4 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR5COMMENT = models.CharField(max_length=100, null=True, blank=True)
    MNTFR5DATEFF = models.DateField(null=True, blank=True)
    MNTFR5PER = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFR5 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR5 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR1COMMENT = models.CharField(max_length=100, null=True, blank=True)
    MNTFR1DATEFF = models.DateField(null=True, blank=True)
    MNTFR1PER = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFR1 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR1 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR3 = models.CharField(max_length=100, null=True, blank=True)
    MNTTAXFR3 = models.CharField(max_length=100, null=True, blank=True)
    MNTFR3PER = models.CharField(max_length=100, null=True, blank=True)
    MNTFR3DATEFF = models.DateField(null=True, blank=True)
    MNTFR4COMMENT = models.CharField(max_length=100, null=True, blank=True)
    XTAXFRAIS5 = models.CharField(max_length=100, null=True, blank=True)
    XTAXFRAIS3 = models.CharField(max_length=100, null=True, blank=True)
    XTAXFRAIS4 = models.CharField(max_length=100, null=True, blank=True)
    XTAXFRAIS2 = models.CharField(max_length=100, null=True, blank=True)
    XTAXFRAIS1 = models.CharField(max_length=100, null=True, blank=True)
    NOOPERSUBCONT = models.CharField(max_length=100, null=True, blank=True)
    XFORBEARANCE = models.CharField(max_length=100, null=True, blank=True)
    FORBEARANCEMOTIF = models.CharField(max_length=100, null=True, blank=True)
    FORBEARANCEDATDEP = models.DateField(null=True, blank=True)
    DATSIGN = models.DateField(null=True, blank=True)
    TXTAXPEN = models.CharField(max_length=100, null=True, blank=True)
    MNTFR3COMMENT = models.CharField(max_length=100, null=True, blank=True)
    XSKIPJOURFERIE = models.CharField(max_length=100, null=True, blank=True)
    DATRMBORIG = models.DateField(null=True, blank=True)

    class Meta:
        db_table = 'prtcli'


class Prtcamo(models.Model):
    NOOPER = models.CharField(max_length=255,primary_key=True)
    NUMSEQ = models.CharField(max_length=255)
    NORMB = models.CharField(max_length=255)
    NOAMO = models.CharField(max_length=255)
    DATRMB = models.DateField()
    MNTRMB = models.CharField(max_length=255)
    MNTINT = models.DecimalField(max_digits=3000,decimal_places=2)
    MNTASS = models.CharField(max_length=255)
    MNTCAP = models.DecimalField(max_digits=3000,decimal_places=2)
    DATREG = models.DateField(null=True)
    TYPAMO = models.CharField(max_length=255)
    MNTAGI = models.CharField(max_length=255)
    MNTDEC = models.CharField(max_length=255)
    SLDAMO = models.CharField(max_length=255)
    DATMAJ = models.DateField()
    DATRMB_X = models.DateField(null=True)
    MNTTAXE = models.DecimalField(max_digits=3000,decimal_places=2)
    DATDERNC = models.DateField(null=True)
    TXDB = models.CharField(max_length=255)
    DATREVTX = models.DateField(null=True)
    MNTFRAIS = models.CharField(max_length=255)
    MNTFRTAX = models.CharField(max_length=255)
    MNTTIMBRE = models.CharField(max_length=255)
    MNTTAXFRAISDIV = models.CharField(max_length=255)
    MNTFRAISDIV = models.CharField(max_length=255)
    DATEFFTX = models.DateField(null=True)
    DATTHEORMB = models.DateField(null=True)
    MNTCAP_PART = models.CharField(max_length=255)
    MNTINT_PART = models.CharField(max_length=255)
    MNTTAXE_PART = models.CharField(max_length=255)
    MNT_INTRET_PART = models.CharField(max_length=255)
    MNTASS_PART = models.CharField(max_length=255)
    TAXASS = models.CharField(max_length=255)
    NOOPERVIR = models.CharField(max_length=255, null=True)
    MNTINTMRG = models.CharField(max_length=255, null=True)
    MNTINTIND = models.CharField(max_length=255, null=True)
    MNTINTSPR = models.CharField(max_length=255, null=True)
    MNTINTRET = models.CharField(max_length=255, null=True)

    class Meta:
        db_table = 'prtcamo'

