# Generated by Django 5.0.1 on 2024-05-13 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prtcamo',
            fields=[
                ('NOOPER', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('NUMSEQ', models.CharField(max_length=255)),
                ('NORMB', models.CharField(max_length=255)),
                ('NOAMO', models.CharField(max_length=255)),
                ('DATRMB', models.DateField()),
                ('MNTRMB', models.CharField(max_length=255)),
                ('MNTINT', models.DecimalField(decimal_places=2, max_digits=3000)),
                ('MNTASS', models.CharField(max_length=255)),
                ('MNTCAP', models.DecimalField(decimal_places=2, max_digits=3000)),
                ('DATREG', models.DateField(null=True)),
                ('TYPAMO', models.CharField(max_length=255)),
                ('MNTAGI', models.CharField(max_length=255)),
                ('MNTDEC', models.CharField(max_length=255)),
                ('SLDAMO', models.CharField(max_length=255)),
                ('DATMAJ', models.DateField()),
                ('DATRMB_X', models.DateField(null=True)),
                ('MNTTAXE', models.DecimalField(decimal_places=2, max_digits=3000)),
                ('DATDERNC', models.DateField(null=True)),
                ('TXDB', models.CharField(max_length=255)),
                ('DATREVTX', models.DateField(null=True)),
                ('MNTFRAIS', models.CharField(max_length=255)),
                ('MNTFRTAX', models.CharField(max_length=255)),
                ('MNTTIMBRE', models.CharField(max_length=255)),
                ('MNTTAXFRAISDIV', models.CharField(max_length=255)),
                ('MNTFRAISDIV', models.CharField(max_length=255)),
                ('DATEFFTX', models.DateField(null=True)),
                ('DATTHEORMB', models.DateField(null=True)),
                ('MNTCAP_PART', models.CharField(max_length=255)),
                ('MNTINT_PART', models.CharField(max_length=255)),
                ('MNTTAXE_PART', models.CharField(max_length=255)),
                ('MNT_INTRET_PART', models.CharField(max_length=255)),
                ('MNTASS_PART', models.CharField(max_length=255)),
                ('TAXASS', models.CharField(max_length=255)),
                ('NOOPERVIR', models.CharField(max_length=255, null=True)),
                ('MNTINTMRG', models.CharField(max_length=255, null=True)),
                ('MNTINTIND', models.CharField(max_length=255, null=True)),
                ('MNTINTSPR', models.CharField(max_length=255, null=True)),
                ('MNTINTRET', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'prtcamo',
            },
        ),
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.CharField(max_length=16),
        ),
    ]
